# Site settings
title: Andrea Ruth Coravos
email: acoravos@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello! I'm starting a new adventure as a student at Dev Bootcamp. I write about life as a millennial, careers, productivity, design-thinking, and gender.
baseurl: "/coravos/" # the subpath of your site, e.g. /blog/
url: "http://acoravos.github.io" # the base hostname & protocol for your site
twitter_username: andreacoravos
github_username:  acoravos

# Build settings
markdown: kramdown
